// GENERATED by scripts/generate-skins.mjs — do not edit.
// Source of truth: shared/skins.json

export const SKINS = ["nebula","ink","slate","grove","prism"];

export const SKIN_NAMES = {
  nebula: { vi: "Nebula", en: "Nebula" },
  ink: { vi: "Ink", en: "Ink" },
  slate: { vi: "Slate", en: "Slate" },
  grove: { vi: "Grove", en: "Grove" },
  prism: { vi: "Prism", en: "Prism" },
};
