/* GENERATED FILE — do not edit by hand.
 * Source: shared/strings.json
 * Regenerate: node scripts/generate-strings.mjs
 */

export const LOCALES = ["vi","en"];

export const STRINGS = {
  "vi": {
    "app.title": "Block Fall",
    "app.tagline": "Xếp khối, phá hàng.",
    "hud.score": "Điểm",
    "hud.best": "Kỷ lục",
    "hud.lines": "Hàng",
    "hud.combo": "Chuỗi",
    "btn.newGame": "Ván mới",
    "btn.undo": "Hoàn tác",
    "btn.settings": "Cài đặt",
    "btn.close": "Đóng",
    "btn.playAgain": "Chơi lại",
    "btn.howTo": "Cách chơi",
    "mode.classic": "Tự do",
    "mode.daily": "Hằng ngày",
    "mode.dailyNote": "Mọi người nhận cùng một bàn cờ mỗi ngày.",
    "over.title": "Hết nước đi",
    "over.why": "Không còn chỗ nào đặt được ba khối còn lại.",
    "over.score": "Bạn được {score} điểm",
    "over.newBest": "Kỷ lục mới!",
    "over.lines": "{lines} hàng đã phá",
    "over.bestCombo": "Chuỗi cao nhất: {combo}",
    "settings.title": "Cài đặt",
    "settings.skin": "Giao diện",
    "settings.sound": "Âm thanh",
    "settings.on": "Bật",
    "settings.off": "Tắt",
    "settings.language": "Ngôn ngữ",
    "settings.privacy": "Không quảng cáo, không tài khoản, không gửi dữ liệu đi đâu.",
    "howto.title": "Cách chơi",
    "howto.1": "Kéo một khối từ khay xuống bàn cờ.",
    "howto.2": "Lấp đầy một hàng hoặc một cột để phá nó.",
    "howto.3": "Phá nhiều hàng cùng lúc được nhiều điểm hơn.",
    "howto.4": "Khối không xoay được — hãy tính trước chỗ đặt.",
    "howto.5": "Hết chỗ đặt cả ba khối là kết thúc ván.",
    "toast.newGame": "Ván mới",
    "toast.undo": "Đã hoàn tác",
    "toast.noUndo": "Hết lượt hoàn tác",
    "toast.dailyDone": "Bàn hôm nay đã xong — quay lại vào ngày mai",
    "toast.perfect": "Sạch bàn! +200 · đổi giao diện",
    "combo.x": "Chuỗi x{n}",
    "clear.single": "Sạch!",
    "clear.double": "Đúp!",
    "clear.triple": "Ba hàng!",
    "clear.quad": "Tuyệt vời!"
  },
  "en": {
    "app.title": "Block Fall",
    "app.tagline": "Drop blocks, clear lines.",
    "hud.score": "Score",
    "hud.best": "Best",
    "hud.lines": "Lines",
    "hud.combo": "Combo",
    "btn.newGame": "New game",
    "btn.undo": "Undo",
    "btn.settings": "Settings",
    "btn.close": "Close",
    "btn.playAgain": "Play again",
    "btn.howTo": "How to play",
    "mode.classic": "Classic",
    "mode.daily": "Daily",
    "mode.dailyNote": "Everyone gets the same board each day.",
    "over.title": "No moves left",
    "over.why": "None of the three remaining blocks fits anywhere.",
    "over.score": "You scored {score}",
    "over.newBest": "New best!",
    "over.lines": "{lines} lines cleared",
    "over.bestCombo": "Best combo: {combo}",
    "settings.title": "Settings",
    "settings.skin": "Skin",
    "settings.sound": "Sound",
    "settings.on": "On",
    "settings.off": "Off",
    "settings.language": "Language",
    "settings.privacy": "No ads, no accounts, nothing sent anywhere.",
    "howto.title": "How to play",
    "howto.1": "Drag a block from the tray onto the board.",
    "howto.2": "Fill a whole row or column to clear it.",
    "howto.3": "Clearing several lines at once scores more.",
    "howto.4": "Blocks do not rotate — plan where they go.",
    "howto.5": "The run ends when no block fits.",
    "toast.newGame": "New game",
    "toast.undo": "Undone",
    "toast.noUndo": "No undos left",
    "toast.dailyDone": "Today's board is done — come back tomorrow",
    "toast.perfect": "Board cleared! +200 · new skin",
    "combo.x": "Combo x{n}",
    "clear.single": "Clear!",
    "clear.double": "Double!",
    "clear.triple": "Triple!",
    "clear.quad": "Superb!"
  }
};
